apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-task
spec:
  steps:
    - name: install-and-build
      image: node:16
      script: |
        npm install
        npm run build

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-task
spec:
  steps:
    - name: run-tests
      image: node:16
      script: |
        npm install
        npx jasmine
